import type { CurrentRoute } from "./types";

export const DEFAULT_CURRENT_ROUTE: CurrentRoute = {
  trip: {
    id: "trip-4811",
    trip_code: "RT-14",
    status: "in_transit",
    dispatch_date: "2026-10-03",
    seal_number: "SL-90821-B",
    vehicle: {
      id: "VEH001",
      reg_number: "NP-4811",
      model_name: "Isuzu ELF NPR Reefer",
      type: "truck",
      temp: "reefer",
      weight_cap_kg: 4200,
      volume_cap_m3: 28.0,
      fuel_type: "diesel",
      km_per_l: 6.8,
      weekly_fuel_quota_l: 120,
      fuel_remaining_l: 84.5,
      reefer_current_temp_c: -18.2,
      reefer_target_temp_c: -18.0,
    },
    depot: {
      id: "depot-01",
      code: "PEL",
      name: "Peliyagoda Central DC",
      lat: 6.9654,
      lng: 79.8872,
    },
    driver: {
      id: "drv-01",
      name: "Saman Perera",
      phone: "+94 77 123 4567",
      license_id: "DL-90821-WP-89",
      designation: "Senior Heavy Vehicle Pilot",
      avatar_initials: "SP",
    },
  },
  active_waypoint_seq: 2,
  waypoints: [
    {
      id: "leg-001",
      route_leg_id: "leg-001",
      seq: 1,
      outlet_id: "OUT001",
      outlet_name: "Waypoint Fresh - Colpetty",
      address: "284 Galle Road, Colpetty, Colombo 03",
      lat: 6.9022,
      lng: 79.8519,
      contact_name: "Rohan Silva",
      contact_number: "+94 77 234 5678",
      access_constraints: "normal",
      dock_type: "rear_dock",
      delivery_window: "05:45 - 06:45 AM",
      status: "completed",
      arrived_at: "2026-10-03T05:50:00Z",
      completed_at: "2026-10-03T06:18:00Z",
      order_summary: {
        order_id: "ORD-0890",
        order_ref: "ORD-0890-A",
        total_weight_kg: 420,
        total_crate_count: 6,
        items: [
          {
            id: "item-1-1",
            order_id: "ORD-0890",
            order_ref: "ORD-0890-A",
            package_code: "PKG-88192-A",
            sku: "SKU-SEA-101",
            item_title: "Atlantic Salmon Fillets & Chilled Poultry",
            category: "Seafood & Poultry",
            crate_count: 3,
            weight_kg: 210,
            volume_m3: 1.4,
            special_handling_code: "COL",
            status: "delivered",
          },
          {
            id: "item-1-2",
            order_id: "ORD-0890",
            order_ref: "ORD-0890-B",
            package_code: "PKG-88192-B",
            sku: "SKU-DAI-204",
            item_title: "Imported Butter & Dairy Blocks",
            category: "Dairy & Butter",
            crate_count: 3,
            weight_kg: 210,
            volume_m3: 1.4,
            special_handling_code: "COL",
            status: "delivered",
          },
        ],
      },
    },
    {
      id: "leg-002",
      route_leg_id: "leg-002",
      seq: 2,
      outlet_id: "OUT002",
      outlet_name: "Waypoint Fresh - Wattala",
      address: "412 Negombo Road, Wattala Central",
      lat: 6.9892,
      lng: 79.8912,
      contact_name: "Chaminda Rathnayake",
      contact_number: "+94 72 331 4455",
      access_constraints: "normal",
      dock_type: "rear_dock",
      delivery_window: "06:30 - 07:30 AM",
      status: "pending",
      order_summary: {
        order_id: "ORD-0891",
        order_ref: "ORD-0891-A",
        total_weight_kg: 780,
        total_crate_count: 54,
        items: [
          {
            id: "item-2-1",
            order_id: "ORD-0891",
            order_ref: "ORD-0891-A",
            package_code: "PKG-90412-A",
            sku: "SKU-SEA-309",
            item_title: "Yellowfin Tuna Loins & Prime Seafood",
            category: "Seafood",
            crate_count: 18,
            weight_kg: 260,
            volume_m3: 1.8,
            special_handling_code: "COL",
            status: "pending",
          },
          {
            id: "item-2-2",
            order_id: "ORD-0891",
            order_ref: "ORD-0891-B",
            package_code: "PKG-90412-B",
            sku: "SKU-DAI-210",
            item_title: "Chilled Farm Butter & Dairy Blocks",
            category: "Dairy",
            crate_count: 18,
            weight_kg: 260,
            volume_m3: 1.6,
            special_handling_code: "COL",
            status: "pending",
          },
          {
            id: "item-2-3",
            order_id: "ORD-0891",
            order_ref: "ORD-0891-C",
            package_code: "PKG-90412-C",
            sku: "SKU-MEA-882",
            item_title: "Free-range Poultry & Chilled Cuts",
            category: "Meat & Poultry",
            crate_count: 18,
            weight_kg: 260,
            volume_m3: 1.9,
            special_handling_code: "COL",
            status: "pending",
          },
        ],
      },
    },
    {
      id: "leg-003",
      route_leg_id: "leg-003",
      seq: 3,
      outlet_id: "OUT003",
      outlet_name: "Waypoint Fresh - Dehiwala",
      address: "88 Galle Road, Dehiwala Junction",
      lat: 6.8524,
      lng: 79.8654,
      contact_name: "Sunil Gunawardena",
      contact_number: "+94 76 554 9900",
      access_constraints: "normal",
      dock_type: "rear_dock",
      delivery_window: "07:15 - 08:15 AM",
      status: "pending",
      order_summary: {
        order_id: "ORD-0892",
        order_ref: "ORD-0892-A",
        total_weight_kg: 540,
        total_crate_count: 8,
        items: [
          {
            id: "item-3-1",
            order_id: "ORD-0892",
            order_ref: "ORD-0892-A",
            package_code: "PKG-91204-A",
            sku: "SKU-MEA-412",
            item_title: "Frozen Organic Beef Cuts",
            category: "Meat & Poultry",
            crate_count: 8,
            weight_kg: 540,
            volume_m3: 3.2,
            special_handling_code: "COL",
            status: "pending",
          },
        ],
      },
    },
    {
      id: "leg-004",
      route_leg_id: "leg-004",
      seq: 4,
      outlet_id: "OUT004",
      outlet_name: "Waypoint Fresh - Havelock City",
      address: "284 Havelock Rd, Cold Vault 3",
      lat: 6.8791,
      lng: 79.8732,
      contact_name: "Priyantha Kumara",
      contact_number: "+94 77 990 1144",
      access_constraints: "mall_dock",
      dock_type: "mall_bay",
      delivery_window: "08:00 - 09:30 AM",
      status: "pending",
      order_summary: {
        order_id: "ORD-0893",
        order_ref: "ORD-0893-A",
        total_weight_kg: 260,
        total_crate_count: 4,
        items: [
          {
            id: "item-4-1",
            order_id: "ORD-0893",
            order_ref: "ORD-0893-A",
            package_code: "PKG-92011-A",
            sku: "SKU-DAI-880",
            item_title: "Artisanal Cheese & Gourmet Dairy",
            category: "Dairy & Bakery",
            crate_count: 2,
            weight_kg: 130,
            volume_m3: 0.9,
            special_handling_code: "MAL",
            status: "pending",
          },
          {
            id: "item-4-2",
            order_id: "ORD-0893",
            order_ref: "ORD-0893-B",
            package_code: "PKG-92011-B",
            sku: "SKU-BEV-108",
            item_title: "Chilled Farm Milk Crates (1L x 12)",
            category: "Dairy & Beverages",
            crate_count: 2,
            weight_kg: 130,
            volume_m3: 0.9,
            special_handling_code: "COL",
            status: "pending",
          },
        ],
      },
    },
  ],
};
