import type { BayWithManifest, TripChecklist } from "./types";

export const MOCK_CARGO_BAYS: BayWithManifest[] = [
  {
    bay: {
      id: "bay-alloc-01",
      bay_number: "Bay 4C",
      depot_id: "depot-pel",
      vehicle_id: "veh-01",
      trip_id: "trip-01",
      dock_status: "docked_loading",
      started_at: "2026-10-03T05:00:00.000Z",
      completed_at: null,
    },
    vehicle: {
      id: "veh-01",
      vehicle_id: "VEH001",
      reg_number: "NP-4811",
      model_name: "Isuzu ELF NPR",
      type: "truck",
      temp: "reefer",
      weight_cap_kg: 4200,
      volume_cap_m3: 28.0,
    },
    driver: {
      name: "Saman Perera",
      phone: "+94 77 123 4567",
      license_number: "DL-90821-WP-89",
    },
    trip: {
      id: "trip-01",
      trip_code: "RT-14",
      dispatch_date: "2026-10-03",
      planned_departure_time: "06:30:00",
      stops_count: 3,
      next_stop_name: "Waypoint Fresh Wattala",
      status: "loading",
    },
    progress: {
      verified_items_count: 2,
      total_items_count: 4,
      verified_crates_count: 40,
      total_crates_count: 80,
      payload_kg: 3360,
      max_payload_kg: 4200,
      payload_percentage: 80,
      volume_m3: 22.4,
      max_volume_m3: 28.0,
      volume_percentage: 80,
    },
  },
  {
    bay: {
      id: "bay-alloc-02",
      bay_number: "Bay 2A",
      depot_id: "depot-pel",
      vehicle_id: "veh-02",
      trip_id: "trip-02",
      dock_status: "docked_loading",
      started_at: "2026-10-03T05:30:00.000Z",
      completed_at: null,
    },
    vehicle: {
      id: "veh-02",
      vehicle_id: "VEH002",
      reg_number: "WP-NE-3120",
      model_name: "Mitsubishi Fuso Canter",
      type: "truck",
      temp: "ambient",
      weight_cap_kg: 6000,
      volume_cap_m3: 22.0,
    },
    driver: {
      name: "Ruwan Silva",
      phone: "+94 71 456 7890",
      license_number: "DL-48190-WP-92",
    },
    trip: {
      id: "trip-02",
      trip_code: "RT-08",
      dispatch_date: "2026-10-03",
      planned_departure_time: "08:00:00",
      stops_count: 3,
      next_stop_name: "Keells Super - Wattala",
      status: "loading",
    },
    progress: {
      verified_items_count: 3,
      total_items_count: 3,
      verified_crates_count: 168,
      total_crates_count: 168,
      payload_kg: 4920,
      max_payload_kg: 6000,
      payload_percentage: 82,
      volume_m3: 17.8,
      max_volume_m3: 22.0,
      volume_percentage: 81,
    },
  },
  {
    bay: {
      id: "bay-alloc-03",
      bay_number: "Bay 1C",
      depot_id: "depot-kandy",
      vehicle_id: "veh-03",
      trip_id: "trip-03",
      dock_status: "docked_loading",
      started_at: "2026-10-03T06:00:00.000Z",
      completed_at: null,
    },
    vehicle: {
      id: "veh-03",
      vehicle_id: "VEH003",
      reg_number: "CP-1192",
      model_name: "Nissan Urvan",
      type: "van",
      temp: "reefer",
      weight_cap_kg: 1500,
      volume_cap_m3: 10.0,
    },
    driver: {
      name: "Roshan Bandara",
      phone: "+94 70 334 5511",
      license_number: "DL-11928-CP-44",
    },
    trip: {
      id: "trip-03",
      trip_code: "RT-16",
      dispatch_date: "2026-10-03",
      planned_departure_time: "07:15:00",
      stops_count: 2,
      next_stop_name: "Waypoint Fresh Kandy Central",
      status: "loading",
    },
    progress: {
      verified_items_count: 0,
      total_items_count: 2,
      verified_crates_count: 0,
      total_crates_count: 52,
      payload_kg: 1100,
      max_payload_kg: 1500,
      payload_percentage: 73,
      volume_m3: 7.2,
      max_volume_m3: 10.0,
      volume_percentage: 72,
    },
  },
];

export const MOCK_TRIP_CHECKLISTS: Record<string, TripChecklist> = {
  "trip-01": {
    trip: {
      id: "trip-01",
      trip_code: "RT-14",
      dispatch_date: "2026-10-03",
      status: "loading",
      vehicle_id: "VEH001",
      vehicle_reg: "NP-4811",
      driver_name: "Saman Perera",
      depot_id: "depot-pel",
      dock_bay: "Bay 4C",
      seal_number: "SL-90821-B",
    },
    waypoints: [
      {
        seq: 2,
        outlet_id: "OUT003",
        outlet_code: "OUT003",
        outlet_name: "Arpico Supercentre - Hyde Park",
        dock_type: "street",
        parking_constraint: "normal",
        delivery_window: "11:30 - 13:00",
        is_sealed: false,
        items: [
          {
            id: "item-01-2-1",
            trip_id: "trip-01",
            order_item_id: "oi-301",
            package_code: "PKG-88301-A",
            sku: "SKU-DAI-201",
            item_title: "Hyde Park Dairy & Butter Section",
            category: "Dairy & Butter",
            staging_bay: "Bay 4C",
            crate_count: 20,
            gross_weight_kg: 680,
            gross_volume_m3: 4.8,
            is_reefer: true,
            special_handling_code: "COL",
            verification_status: "pending",
          },
        ],
      },
      {
        seq: 1,
        outlet_id: "OUT002",
        outlet_code: "OUT002",
        outlet_name: "Keells Super - Kollupitiya",
        dock_type: "rear_dock",
        parking_constraint: "normal",
        delivery_window: "09:30 - 11:00",
        is_sealed: false,
        items: [
          {
            id: "item-01-1-1",
            trip_id: "trip-01",
            order_item_id: "oi-201",
            package_code: "PKG-44819-A",
            sku: "SKU-MEA-401",
            item_title: "Kollupitiya Meat & Frozen Poultry",
            category: "Meat & Poultry",
            staging_bay: "Bay 4C",
            crate_count: 28,
            gross_weight_kg: 1120,
            gross_volume_m3: 7.2,
            is_reefer: true,
            special_handling_code: "COL",
            verification_status: "verified",
            verified_at: "2026-10-03T05:15:00.000Z",
          },
        ],
      },
      {
        seq: 0,
        outlet_id: "OUT001",
        outlet_code: "OUT001",
        outlet_name: "Waypoint Fresh Wattala",
        dock_type: "rear_dock",
        parking_constraint: "normal",
        delivery_window: "07:30 - 09:00",
        is_sealed: true,
        sealed_at: "2026-10-03T05:10:00.000Z",
        items: [
          {
            id: "item-01-0-1",
            trip_id: "trip-01",
            order_item_id: "oi-101",
            package_code: "PKG-72610-A",
            sku: "SKU-SEA-101",
            item_title: "Fresh Seafood & Chilled Milk Crates",
            category: "Seafood & Dairy",
            staging_bay: "Bay 4C",
            crate_count: 32,
            gross_weight_kg: 1560,
            gross_volume_m3: 10.4,
            is_reefer: true,
            special_handling_code: "COL",
            verification_status: "verified",
            verified_at: "2026-10-03T05:08:00.000Z",
          },
        ],
      },
    ],
    summary: {
      total_waypoints: 3,
      sealed_waypoints: 1,
      total_items: 3,
      verified_items: 2,
      is_ready_for_departure: false,
    },
  },
};
