export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export type Role = "system_admin" | "dispatcher" | "loader" | "driver" | "store_manager";

export type EndpointStatus = "live" | "pending";

export type ApiDomain =
  | "auth"
  | "users"
  | "guards"
  | "master"
  | "fleet"
  | "telemetry"
  | "orders"
  | "deferrals"
  | "allocations"
  | "loader"
  | "driver"
  | "deliveries"
  | "sync"
  | "system";

export interface ApiEndpoint {
  readonly domain: ApiDomain;
  readonly method: HttpMethod;
  readonly path: string;
  readonly roles: readonly Role[];
  readonly offline: boolean;
  readonly status: EndpointStatus;
  readonly issue: number | null;
  readonly ui: boolean;
}

export const ENDPOINTS = {
  // 1. Auth & Users
  authLogin: {
    domain: "auth",
    method: "POST",
    path: "/auth/jwt/login",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  authLogout: {
    domain: "auth",
    method: "POST",
    path: "/auth/jwt/logout",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  authForgotPassword: {
    domain: "auth",
    method: "POST",
    path: "/auth/forgot-password",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  authResetPassword: {
    domain: "auth",
    method: "POST",
    path: "/auth/reset-password",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  authRefresh: {
    domain: "auth",
    method: "POST",
    path: "/auth/refresh",
    roles: [],
    offline: false,
    status: "pending",
    issue: 6,
    ui: false,
  },
  usersMe: {
    domain: "users",
    method: "GET",
    path: "/users/me",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  usersUpdateMe: {
    domain: "users",
    method: "PATCH",
    path: "/users/me",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  usersList: {
    domain: "users",
    method: "GET",
    path: "/users",
    roles: ["system_admin"],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  usersCreate: {
    domain: "users",
    method: "POST",
    path: "/users",
    roles: ["system_admin"],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  usersGet: {
    domain: "users",
    method: "GET",
    path: "/users/{id}",
    roles: ["system_admin"],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  usersUpdate: {
    domain: "users",
    method: "PATCH",
    path: "/users/{id}",
    roles: ["system_admin"],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  usersDelete: {
    domain: "users",
    method: "DELETE",
    path: "/users/{id}",
    roles: ["system_admin"],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },

  // Guards
  guardAdminOnly: {
    domain: "guards",
    method: "GET",
    path: "/guards/admin-only",
    roles: ["system_admin"],
    offline: false,
    status: "live",
    issue: null,
    ui: false,
  },
  guardStoreManager: {
    domain: "guards",
    method: "GET",
    path: "/guards/store-manager",
    roles: ["store_manager"],
    offline: false,
    status: "live",
    issue: null,
    ui: false,
  },
  guardDriver: {
    domain: "guards",
    method: "GET",
    path: "/guards/driver",
    roles: ["driver"],
    offline: false,
    status: "live",
    issue: null,
    ui: false,
  },

  // 2. Master Domain
  masterDepotsList: {
    domain: "master",
    method: "GET",
    path: "/master/depots",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterDepotsGet: {
    domain: "master",
    method: "GET",
    path: "/master/depots/{id}",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterDepotsUpdate: {
    domain: "master",
    method: "PUT",
    path: "/master/depots/{id}",
    roles: ["system_admin"],
    offline: false,
    status: "pending",
    issue: 7,
    ui: true,
  },
  masterDistrictsList: {
    domain: "master",
    method: "GET",
    path: "/master/districts",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterBrandsList: {
    domain: "master",
    method: "GET",
    path: "/master/brands",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterOutletsList: {
    domain: "master",
    method: "GET",
    path: "/master/outlets",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterOutletsGet: {
    domain: "master",
    method: "GET",
    path: "/master/outlets/{id}",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterOutletsCreate: {
    domain: "master",
    method: "POST",
    path: "/master/outlets",
    roles: ["system_admin"],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterOutletsUpdate: {
    domain: "master",
    method: "PUT",
    path: "/master/outlets/{id}",
    roles: ["system_admin"],
    offline: false,
    status: "pending",
    issue: 7,
    ui: true,
  },
  masterOutletsDelete: {
    domain: "master",
    method: "DELETE",
    path: "/master/outlets/{id}",
    roles: ["system_admin"],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterItemsList: {
    domain: "master",
    method: "GET",
    path: "/master/items",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterItemsGet: {
    domain: "master",
    method: "GET",
    path: "/master/items/{id}",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterItemsCreate: {
    domain: "master",
    method: "POST",
    path: "/master/items",
    roles: ["system_admin"],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterItemsUpdate: {
    domain: "master",
    method: "PUT",
    path: "/master/items/{id}",
    roles: ["system_admin"],
    offline: false,
    status: "pending",
    issue: 7,
    ui: true,
  },
  masterItemsDelete: {
    domain: "master",
    method: "DELETE",
    path: "/master/items/{id}",
    roles: ["system_admin"],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterPricesList: {
    domain: "master",
    method: "GET",
    path: "/master/prices",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterPricesListActive: {
    domain: "master",
    method: "GET",
    path: "/master/prices/active",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterPricesGetByItem: {
    domain: "master",
    method: "GET",
    path: "/master/prices/items/{item_id}/active",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterPricesCreate: {
    domain: "master",
    method: "POST",
    path: "/master/prices",
    roles: ["system_admin"],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterPricesUpdate: {
    domain: "master",
    method: "PUT",
    path: "/master/prices/{id}",
    roles: ["system_admin"],
    offline: false,
    status: "pending",
    issue: 7,
    ui: true,
  },
  masterCalendarOperatingDays: {
    domain: "master",
    method: "GET",
    path: "/master/calendar/operating-days",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterCalendarSurge: {
    domain: "master",
    method: "GET",
    path: "/master/calendar/surge",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterCalendarRange: {
    domain: "master",
    method: "GET",
    path: "/master/calendar",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterCalendarBulkGenerate: {
    domain: "master",
    method: "POST",
    path: "/master/calendar/bulk-generate",
    roles: ["system_admin"],
    offline: false,
    status: "live",
    issue: null,
    ui: true,
  },
  masterCalendarUpdateDay: {
    domain: "master",
    method: "PUT",
    path: "/master/calendar/{date}",
    roles: ["system_admin"],
    offline: false,
    status: "pending",
    issue: 7,
    ui: true,
  },

  // 3. Fleet & Vehicles
  fleetVehiclesList: {
    domain: "fleet",
    method: "GET",
    path: "/fleet/vehicles",
    roles: [],
    offline: false,
    status: "pending",
    issue: 8,
    ui: true,
  },
  fleetVehiclesGet: {
    domain: "fleet",
    method: "GET",
    path: "/fleet/vehicles/{id}",
    roles: [],
    offline: false,
    status: "pending",
    issue: 8,
    ui: true,
  },
  fleetVehiclesCreate: {
    domain: "fleet",
    method: "POST",
    path: "/fleet/vehicles",
    roles: ["system_admin"],
    offline: false,
    status: "pending",
    issue: 8,
    ui: true,
  },
  fleetVehiclesUpdate: {
    domain: "fleet",
    method: "PATCH",
    path: "/fleet/vehicles/{id}",
    roles: ["dispatcher", "system_admin"],
    offline: false,
    status: "pending",
    issue: 8,
    ui: true,
  },
  fleetDriversList: {
    domain: "fleet",
    method: "GET",
    path: "/fleet/drivers",
    roles: [],
    offline: false,
    status: "pending",
    issue: 8,
    ui: true,
  },

  // 4. Fleet Telemetry
  telemetryReport: {
    domain: "telemetry",
    method: "POST",
    path: "/fleet/telemetry/report",
    roles: ["driver"],
    offline: true,
    status: "pending",
    issue: 9,
    ui: true,
  },
  telemetryLive: {
    domain: "telemetry",
    method: "GET",
    path: "/fleet/telemetry/live",
    roles: ["dispatcher", "system_admin"],
    offline: false,
    status: "pending",
    issue: 9,
    ui: true,
  },
  telemetryVehicleLatest: {
    domain: "telemetry",
    method: "GET",
    path: "/fleet/vehicles/{id}/telemetry/latest",
    roles: [],
    offline: false,
    status: "pending",
    issue: 9,
    ui: true,
  },

  // 5. Store Orders
  ordersCreate: {
    domain: "orders",
    method: "POST",
    path: "/orders",
    roles: ["store_manager", "system_admin"],
    offline: true,
    status: "pending",
    issue: 10,
    ui: true,
  },
  ordersList: {
    domain: "orders",
    method: "GET",
    path: "/orders",
    roles: [],
    offline: false,
    status: "pending",
    issue: 10,
    ui: true,
  },
  ordersGet: {
    domain: "orders",
    method: "GET",
    path: "/orders/{id}",
    roles: [],
    offline: false,
    status: "pending",
    issue: 10,
    ui: true,
  },
  ordersUpdateStatus: {
    domain: "orders",
    method: "PATCH",
    path: "/orders/{id}/status",
    roles: ["dispatcher", "system_admin"],
    offline: false,
    status: "pending",
    issue: 10,
    ui: true,
  },

  // 6. Order Deferrals
  deferralsDeferOrder: {
    domain: "deferrals",
    method: "POST",
    path: "/orders/{id}/defer",
    roles: ["dispatcher", "system_admin"],
    offline: false,
    status: "pending",
    issue: 11,
    ui: true,
  },
  deferralsList: {
    domain: "deferrals",
    method: "GET",
    path: "/deferrals",
    roles: ["dispatcher", "system_admin"],
    offline: false,
    status: "pending",
    issue: 11,
    ui: true,
  },
  deferralsRequeue: {
    domain: "deferrals",
    method: "POST",
    path: "/deferrals/{id}/re-queue",
    roles: ["dispatcher", "system_admin"],
    offline: false,
    status: "pending",
    issue: 11,
    ui: true,
  },
  deferralsSummary: {
    domain: "deferrals",
    method: "GET",
    path: "/deferrals/summary",
    roles: ["dispatcher", "system_admin"],
    offline: false,
    status: "pending",
    issue: null,
    ui: true,
  },

  // 7. Allocations & Solver
  allocationsList: {
    domain: "allocations",
    method: "GET",
    path: "/allocations",
    roles: ["dispatcher", "system_admin"],
    offline: false,
    status: "pending",
    issue: 12,
    ui: true,
  },
  allocationsGet: {
    domain: "allocations",
    method: "GET",
    path: "/allocations/{id}",
    roles: [],
    offline: false,
    status: "pending",
    issue: 12,
    ui: true,
  },
  allocationsConfirm: {
    domain: "allocations",
    method: "POST",
    path: "/allocations/{id}/confirm",
    roles: ["dispatcher", "system_admin"],
    offline: false,
    status: "pending",
    issue: 12,
    ui: true,
  },
  allocationsSummary: {
    domain: "allocations",
    method: "GET",
    path: "/allocations/summary",
    roles: ["dispatcher", "system_admin"],
    offline: false,
    status: "pending",
    issue: 12,
    ui: true,
  },
  allocationsOptimize: {
    domain: "allocations",
    method: "POST",
    path: "/allocations/optimize",
    roles: ["dispatcher", "system_admin"],
    offline: false,
    status: "pending",
    issue: 16,
    ui: true,
  },
  allocationsSolverStatus: {
    domain: "allocations",
    method: "GET",
    path: "/allocations/engine/status",
    roles: ["dispatcher", "system_admin"],
    offline: false,
    status: "pending",
    issue: 16,
    ui: true,
  },
  allocationsScheduleCron: {
    domain: "allocations",
    method: "POST",
    path: "/allocations/engine/schedule",
    roles: ["system_admin"],
    offline: false,
    status: "pending",
    issue: 16,
    ui: true,
  },

  // 8. Loader Bay Operations
  loaderBays: {
    domain: "loader",
    method: "GET",
    path: "/loader/bays",
    roles: ["loader", "dispatcher", "system_admin"],
    offline: false,
    status: "pending",
    issue: 13,
    ui: true,
  },
  loaderChecklist: {
    domain: "loader",
    method: "GET",
    path: "/loader/trips/{trip_id}/checklist",
    roles: ["loader", "system_admin"],
    offline: true,
    status: "pending",
    issue: 13,
    ui: true,
  },
  loaderVerifyItem: {
    domain: "loader",
    method: "POST",
    path: "/loader/items/{item_id}/verify",
    roles: ["loader"],
    offline: true,
    status: "pending",
    issue: 13,
    ui: true,
  },
  loaderSealWaypoint: {
    domain: "loader",
    method: "POST",
    path: "/loader/trips/{trip_id}/waypoints/{seq}/seal",
    roles: ["loader"],
    offline: true,
    status: "pending",
    issue: 13,
    ui: true,
  },
  loaderConfirmDeparture: {
    domain: "loader",
    method: "POST",
    path: "/loader/trips/{trip_id}/confirm-departure",
    roles: ["loader"],
    offline: true,
    status: "pending",
    issue: 13,
    ui: true,
  },

  // 9. Driver & Deliveries (EPOD)
  driverCurrentRoute: {
    domain: "driver",
    method: "GET",
    path: "/driver/routes/current",
    roles: ["driver"],
    offline: true,
    status: "pending",
    issue: 14,
    ui: true,
  },
  deliveriesArrive: {
    domain: "deliveries",
    method: "POST",
    path: "/deliveries/{waypoint_id}/arrive",
    roles: ["driver"],
    offline: true,
    status: "pending",
    issue: 14,
    ui: true,
  },
  deliveriesPod: {
    domain: "deliveries",
    method: "POST",
    path: "/deliveries/{waypoint_id}/pod",
    roles: ["driver"],
    offline: true,
    status: "pending",
    issue: 14,
    ui: true,
  },
  deliveriesDiscrepancy: {
    domain: "deliveries",
    method: "POST",
    path: "/deliveries/{waypoint_id}/discrepancy",
    roles: ["driver", "store_manager"],
    offline: true,
    status: "pending",
    issue: 14,
    ui: true,
  },

  // 10. Universal Sync
  syncBatch: {
    domain: "sync",
    method: "POST",
    path: "/sync/batch",
    roles: [],
    offline: false,
    status: "pending",
    issue: 15,
    ui: false,
  },

  // 11. System Health & Root
  systemRoot: {
    domain: "system",
    method: "GET",
    path: "/",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: false,
  },
  systemHealth: {
    domain: "system",
    method: "GET",
    path: "/health",
    roles: [],
    offline: false,
    status: "live",
    issue: null,
    ui: false,
  },
} as const satisfies Record<string, ApiEndpoint>;

export const ENDPOINT_LIST: readonly ApiEndpoint[] = Object.values(ENDPOINTS);

export const ENDPOINT_COUNTS = {
  live: ENDPOINT_LIST.filter((ep) => ep.status === "live").length,
  pending: ENDPOINT_LIST.filter((ep) => ep.status === "pending").length,
  total: ENDPOINT_LIST.length,
} as const;
