import type { OrderDetail, SpecialHandlingCode } from "./types";

export interface MockCatalogProduct {
  id: string;
  sku: string;
  name: string;
  category: string;
  brand_id: string;
  unit_weight_kg: number;
  unit_volume_m3: number;
  unit_price: number;
  special_handling_code: SpecialHandlingCode | null;
  requires_cold_chain: boolean;
}

export const MOCK_CATALOG_PRODUCTS: MockCatalogProduct[] = [
  {
    id: "prod-01",
    sku: "SKU-MLK-01",
    name: "Farm Fresh Chilled Full Cream Milk (1L x 24)",
    category: "Dairy & Chilled",
    brand_id: "brand-fresh-01",
    unit_weight_kg: 25.5,
    unit_volume_m3: 0.18,
    unit_price: 11500,
    special_handling_code: "COL",
    requires_cold_chain: true,
  },
  {
    id: "prod-02",
    sku: "SKU-BTR-02",
    name: "Highland Butter Blocks Salted (250g x 40)",
    category: "Dairy & Chilled",
    brand_id: "brand-fresh-01",
    unit_weight_kg: 10.5,
    unit_volume_m3: 0.07,
    unit_price: 14200,
    special_handling_code: "COL",
    requires_cold_chain: true,
  },
  {
    id: "prod-03",
    sku: "SKU-YGT-03",
    name: "Low-Fat Set Yoghurt Cups (80g x 48)",
    category: "Dairy & Chilled",
    brand_id: "brand-fresh-01",
    unit_weight_kg: 4.5,
    unit_volume_m3: 0.04,
    unit_price: 4800,
    special_handling_code: "COL",
    requires_cold_chain: true,
  },
  {
    id: "prod-04",
    sku: "SKU-STR-04",
    name: "Peradeniya Organic Strawberries (500g Crates x 12)",
    category: "Fresh Produce",
    brand_id: "brand-fresh-01",
    unit_weight_kg: 9.05,
    unit_volume_m3: 0.054,
    unit_price: 6300,
    special_handling_code: "FRG",
    requires_cold_chain: false,
  },
  {
    id: "prod-05",
    sku: "SKU-CHK-05",
    name: "Fresh Cut Premium Broiler Chicken (1kg x 15)",
    category: "Meat & Poultry",
    brand_id: "brand-fresh-01",
    unit_weight_kg: 15.5,
    unit_volume_m3: 0.11,
    unit_price: 11800,
    special_handling_code: "COL",
    requires_cold_chain: true,
  },
  {
    id: "prod-06",
    sku: "SKU-EGG-06",
    name: "Local Free-Range Eggs (Crate 30s x 6)",
    category: "Fresh Produce",
    brand_id: "brand-fresh-01",
    unit_weight_kg: 9.4,
    unit_volume_m3: 0.058,
    unit_price: 5640,
    special_handling_code: "FRG",
    requires_cold_chain: false,
  },
  {
    id: "prod-07",
    sku: "SKU-TSH-07",
    name: "Linen Summer Collection T-Shirts (Box 50s)",
    category: "Apparel",
    brand_id: "brand-style-02",
    unit_weight_kg: 12.0,
    unit_volume_m3: 0.09,
    unit_price: 25000,
    special_handling_code: "MAL",
    requires_cold_chain: false,
  },
  {
    id: "prod-08",
    sku: "SKU-PHN-08",
    name: "Pro Smartphone 256GB Midnight Black (Pack 10)",
    category: "Electronics",
    brand_id: "brand-tech-03",
    unit_weight_kg: 4.2,
    unit_volume_m3: 0.035,
    unit_price: 450000,
    special_handling_code: "FRG",
    requires_cold_chain: false,
  },
];

export const INITIAL_SEED_ORDERS: OrderDetail[] = [
  {
    id: "ord-01",
    order_ref: "S1-001",
    outlet_id: "OUT001",
    brand_id: "brand-fresh-01",
    order_date: "2026-10-01",
    required_date: "2026-10-01",
    temp_requirement: "chilled",
    status: "pending",
    is_urgent: true,
    deferred_yesterday: 1,
    days_since_last_served: 2,
    total_weight_kg: 420.5,
    total_volume_m3: 2.85,
    total_price_lkr: 285400,
    created_at: "2026-10-01T04:15:00Z",
    outlet_name: "Waypoint Fresh - Fort Dock",
    outlet_address: "York Street, Colombo 01",
    district: "Colombo",
    depot: "Peliyagoda",
    dock_type: "rear_dock",
    parking_constraint: "normal",
    delivery_window: "05:00 - 08:00 AM",
    items: [
      {
        id: "oi-101",
        order_id: "ord-01",
        item_id: "prod-01",
        package_code: "PKG-90412-A",
        item_name: "Farm Fresh Chilled Full Cream Milk (1L x 24)",
        category: "Dairy & Chilled",
        loaded_qty: 0,
        delivered_qty: 0,
        requested_qty: 10,
        unit_weight_kg: 25.5,
        unit_volume_m3: 0.18,
        unit_price: 11500,
        special_handling_code: "COL",
      },
      {
        id: "oi-102",
        order_id: "ord-01",
        item_id: "prod-02",
        package_code: "PKG-90412-B",
        item_name: "Highland Butter Blocks Salted (250g x 40)",
        category: "Dairy & Chilled",
        requested_qty: 8,
        unit_weight_kg: 10.5,
        unit_volume_m3: 0.07,
        unit_price: 14200,
        special_handling_code: "COL",
      },
      {
        id: "oi-103",
        order_id: "ord-01",
        item_id: "prod-04",
        package_code: "PKG-90412-C",
        item_name: "Peradeniya Organic Strawberries (500g Crates x 12)",
        category: "Fresh Produce",
        requested_qty: 9,
        unit_weight_kg: 9.05,
        unit_volume_m3: 0.054,
        unit_price: 6300,
        special_handling_code: "FRG",
      },
    ],
    fulfillment_history: [
      {
        id: "fh-01",
        order_id: "ord-01",
        status: "pending",
        changed_at: "2026-10-01T04:15:00Z",
        changed_by: "Store Manager",
      },
    ],
  },
  {
    id: "ord-02",
    order_ref: "S1-002",
    outlet_id: "OUT001",
    brand_id: "brand-fresh-01",
    order_date: "2026-10-01",
    required_date: "2026-10-01",
    temp_requirement: "chilled",
    status: "allocated",
    is_urgent: false,
    deferred_yesterday: 0,
    days_since_last_served: 1,
    total_weight_kg: 280.0,
    total_volume_m3: 1.9,
    total_price_lkr: 198000,
    created_at: "2026-10-01T04:30:00Z",
    outlet_name: "Waypoint Fresh - Fort Dock",
    outlet_address: "York Street, Colombo 01",
    district: "Colombo",
    depot: "Peliyagoda",
    dock_type: "rear_dock",
    parking_constraint: "normal",
    delivery_window: "05:00 - 08:00 AM",
    items: [
      {
        id: "oi-201",
        order_id: "ord-02",
        item_id: "prod-05",
        package_code: "PKG-91823-A",
        item_name: "Fresh Cut Premium Broiler Chicken (1kg x 15)",
        category: "Meat & Poultry",
        requested_qty: 12,
        unit_weight_kg: 15.5,
        unit_volume_m3: 0.11,
        unit_price: 11800,
        special_handling_code: "COL",
      },
      {
        id: "oi-202",
        order_id: "ord-02",
        item_id: "prod-06",
        package_code: "PKG-91823-B",
        item_name: "Local Free-Range Eggs (Crate 30s x 6)",
        category: "Fresh Produce",
        requested_qty: 10,
        unit_weight_kg: 9.4,
        unit_volume_m3: 0.058,
        unit_price: 5640,
        special_handling_code: "FRG",
      },
    ],
    fulfillment_history: [
      {
        id: "fh-02a",
        order_id: "ord-02",
        status: "pending",
        changed_at: "2026-10-01T04:30:00Z",
        changed_by: "Store Manager",
      },
      {
        id: "fh-02b",
        order_id: "ord-02",
        status: "allocated",
        changed_at: "2026-10-01T04:45:00Z",
        changed_by: "System Optimizer",
      },
    ],
  },
  {
    id: "ord-03",
    order_ref: "S1-003",
    outlet_id: "OUT002",
    brand_id: "brand-fresh-01",
    order_date: "2026-10-01",
    required_date: "2026-10-01",
    temp_requirement: "chilled",
    status: "in_transit",
    is_urgent: false,
    deferred_yesterday: 0,
    days_since_last_served: 1,
    total_weight_kg: 310.0,
    total_volume_m3: 2.1,
    total_price_lkr: 215000,
    created_at: "2026-10-01T04:50:00Z",
    outlet_name: "Waypoint Fresh - Slave Island",
    outlet_address: "Justice Akbar Mawatha, Colombo 02",
    district: "Colombo",
    depot: "Peliyagoda",
    dock_type: "street",
    parking_constraint: "van_only",
    delivery_window: "05:00 - 08:00 AM",
    items: [
      {
        id: "oi-301",
        order_id: "ord-03",
        item_id: "prod-01",
        package_code: "PKG-92041-A",
        item_name: "Farm Fresh Chilled Full Cream Milk (1L x 24)",
        category: "Dairy & Chilled",
        requested_qty: 8,
        unit_weight_kg: 25.5,
        unit_volume_m3: 0.18,
        unit_price: 11500,
        special_handling_code: "COL",
      },
      {
        id: "oi-302",
        order_id: "ord-03",
        item_id: "prod-03",
        package_code: "PKG-92041-B",
        item_name: "Low-Fat Set Yoghurt Cups (80g x 48)",
        category: "Dairy & Chilled",
        requested_qty: 15,
        unit_weight_kg: 4.5,
        unit_volume_m3: 0.04,
        unit_price: 4800,
        special_handling_code: "COL",
      },
    ],
    fulfillment_history: [
      {
        id: "fh-03a",
        order_id: "ord-03",
        status: "pending",
        changed_at: "2026-10-01T04:50:00Z",
        changed_by: "Store Manager",
      },
      {
        id: "fh-03b",
        order_id: "ord-03",
        status: "allocated",
        changed_at: "2026-10-01T05:00:00Z",
        changed_by: "Dispatcher",
      },
      {
        id: "fh-03c",
        order_id: "ord-03",
        status: "in_transit",
        changed_at: "2026-10-01T05:30:00Z",
        changed_by: "Driver",
      },
    ],
  },
  {
    id: "ord-04",
    order_ref: "S1-004",
    outlet_id: "OUT003",
    brand_id: "brand-fresh-01",
    order_date: "2026-10-01",
    required_date: "2026-10-01",
    temp_requirement: "chilled",
    status: "pending",
    is_urgent: true,
    deferred_yesterday: 1,
    days_since_last_served: 2,
    total_weight_kg: 540.0,
    total_volume_m3: 3.6,
    total_price_lkr: 392000,
    created_at: "2026-10-01T05:10:00Z",
    outlet_name: "Waypoint Fresh - Kollupitiya",
    outlet_address: "Galle Road, Colombo 03",
    district: "Colombo",
    depot: "Peliyagoda",
    dock_type: "rear_dock",
    parking_constraint: "normal",
    delivery_window: "05:00 - 08:00 AM",
    items: [
      {
        id: "oi-401",
        order_id: "ord-04",
        item_id: "prod-01",
        package_code: "PKG-93102-A",
        item_name: "Farm Fresh Chilled Full Cream Milk (1L x 24)",
        category: "Dairy & Chilled",
        requested_qty: 12,
        unit_weight_kg: 25.5,
        unit_volume_m3: 0.18,
        unit_price: 11500,
        special_handling_code: "COL",
      },
      {
        id: "oi-402",
        order_id: "ord-04",
        item_id: "prod-04",
        package_code: "PKG-93102-B",
        item_name: "Peradeniya Organic Strawberries (500g Crates x 12)",
        category: "Fresh Produce",
        requested_qty: 18,
        unit_weight_kg: 9.05,
        unit_volume_m3: 0.054,
        unit_price: 6300,
        special_handling_code: "FRG",
      },
    ],
  },
  {
    id: "ord-05",
    order_ref: "S1-005",
    outlet_id: "OUT004",
    brand_id: "brand-style-02",
    order_date: "2026-10-01",
    required_date: "2026-10-01",
    temp_requirement: "ambient",
    status: "delivered",
    is_urgent: false,
    deferred_yesterday: 0,
    days_since_last_served: 1,
    total_weight_kg: 380.0,
    total_volume_m3: 3.2,
    total_price_lkr: 460000,
    created_at: "2026-10-01T05:20:00Z",
    outlet_name: "Waypoint Style - Bambalapitiya Mall",
    outlet_address: "Duplication Road, Colombo 04",
    district: "Colombo",
    depot: "Peliyagoda",
    dock_type: "mall_bay",
    parking_constraint: "mall_dock",
    delivery_window: "09:00 - 11:00 AM",
    items: [
      {
        id: "oi-501",
        order_id: "ord-05",
        item_id: "prod-07",
        package_code: "PKG-94012-A",
        item_name: "Linen Summer Collection T-Shirts (Box 50s)",
        category: "Apparel",
        requested_qty: 10,
        unit_weight_kg: 12.0,
        unit_volume_m3: 0.09,
        unit_price: 25000,
        special_handling_code: "MAL",
      },
    ],
  },
  {
    id: "ord-06",
    order_ref: "S1-006",
    outlet_id: "OUT005",
    brand_id: "brand-tech-03",
    order_date: "2026-10-01",
    required_date: "2026-10-01",
    temp_requirement: "ambient",
    status: "deferred",
    is_urgent: false,
    deferred_yesterday: 0,
    days_since_last_served: 2,
    total_weight_kg: 42.0,
    total_volume_m3: 0.35,
    total_price_lkr: 4500000,
    created_at: "2026-10-01T05:25:00Z",
    outlet_name: "Waypoint Tech - Havelock City",
    outlet_address: "Havelock Road, Colombo 05",
    district: "Colombo",
    depot: "Peliyagoda",
    dock_type: "mall_bay",
    parking_constraint: "normal",
    delivery_window: "10:00 - 01:00 PM",
    items: [
      {
        id: "oi-601",
        order_id: "ord-06",
        item_id: "prod-08",
        package_code: "PKG-95011-A",
        item_name: "Pro Smartphone 256GB Midnight Black (Pack 10)",
        category: "Electronics",
        requested_qty: 10,
        unit_weight_kg: 4.2,
        unit_volume_m3: 0.035,
        unit_price: 450000,
        special_handling_code: "FRG",
      },
    ],
  },
];
