import type { DeferralAuditLog, DeferralSummary, DeferredOrder } from "./types";

export const INITIAL_DEFERRED_ORDERS: DeferredOrder[] = [
  {
    id: "ord-cov-01",
    order_ref: "S1-004",
    outlet_id: "OUT004",
    outlet_name: "Waypoint Fresh - Wattala",
    brand_id: "brand-fresh-01",
    brand: "Fresh",
    district: "Gampaha",
    dock_type: "street",
    parking_constraint: "van_only",
    temp_requirement: "chilled",
    order_date: "2026-10-01",
    status: "deferred",
    total_items: 4,
    total_weight_kg: 540.0,
    total_volume_m3: 3.2,
    total_price_lkr: 345000,
    deferred_yesterday: 1,
    days_since_last_served: 2,
    deferral_reason: "van_access_shortage",
    latest_reason: "van_access_shortage",
    limiting_resource: "volume_cap",
    suggested_vehicle_category: "Reefer Van (4.5 m³)",
    notes:
      "Street parking allows van-only access. Reefer vans were fully saturated in Wave 1. Mandatory dispatch tomorrow morning.",
    created_at: "2026-10-01T04:15:22Z",
  },
  {
    id: "ord-cov-02",
    order_ref: "S1-018",
    outlet_id: "OUT018",
    outlet_name: "Waypoint Fresh - Kandy City Centre",
    brand_id: "brand-fresh-01",
    brand: "Fresh",
    district: "Kandy",
    dock_type: "mall_bay",
    parking_constraint: "mall_dock",
    temp_requirement: "chilled",
    order_date: "2026-10-01",
    status: "deferred",
    total_items: 5,
    total_weight_kg: 620.0,
    total_volume_m3: 4.1,
    total_price_lkr: 412000,
    deferred_yesterday: 1,
    days_since_last_served: 2,
    deferral_reason: "insufficient_reefer_capacity",
    latest_reason: "insufficient_reefer_capacity",
    limiting_resource: "time_budget",
    suggested_vehicle_category: "Reefer Van / Light Truck",
    notes:
      "Strict Mall Bay delivery window (09:00 - 11:00 AM) exceeded regional driver time budget. Auto-locked into Priority 1 for tomorrow.",
    created_at: "2026-10-01T04:22:10Z",
  },
  {
    id: "ord-cov-03",
    order_ref: "S1-032",
    outlet_id: "OUT032",
    outlet_name: "Waypoint Style - Havelock Town",
    brand_id: "brand-style-01",
    brand: "Style",
    district: "Colombo",
    dock_type: "rear_dock",
    parking_constraint: "normal",
    temp_requirement: "ambient",
    order_date: "2026-10-01",
    status: "deferred",
    total_items: 3,
    total_weight_kg: 380.0,
    total_volume_m3: 4.8,
    total_price_lkr: 680000,
    deferred_yesterday: 0,
    days_since_last_served: 1,
    deferral_reason: "time_budget_limit",
    latest_reason: "time_budget_limit",
    limiting_resource: "time_budget",
    suggested_vehicle_category: "14ft Dry Lorry (12.0 m³)",
    notes:
      "Route exceeded daily driver 480 min budget due to evening traffic along Galle Road. Shifted to tomorrow morning Wave 1.",
    created_at: "2026-10-01T05:01:45Z",
  },
  {
    id: "ord-cov-04",
    order_ref: "S1-045",
    outlet_id: "OUT045",
    outlet_name: "Waypoint Tech - Negombo Retail Hub",
    brand_id: "brand-tech-01",
    brand: "Tech",
    district: "Gampaha",
    dock_type: "rear_dock",
    parking_constraint: "normal",
    temp_requirement: "ambient",
    order_date: "2026-10-01",
    status: "deferred",
    total_items: 2,
    total_weight_kg: 210.0,
    total_volume_m3: 2.4,
    total_price_lkr: 1450000,
    deferred_yesterday: 0,
    days_since_last_served: 1,
    deferral_reason: "fuel_quota_exceeded",
    latest_reason: "fuel_quota_exceeded",
    limiting_resource: "fleet_downtime",
    suggested_vehicle_category: "14ft Dry Lorry / Ambient Van",
    notes:
      "Assigned vehicle underwent scheduled 5000km workshop maintenance. Vehicle returning to active fleet tomorrow at 04:00 AM.",
    created_at: "2026-10-01T05:18:00Z",
  },
];

export const INITIAL_DEFERRAL_SUMMARY: DeferralSummary = {
  total_deferred_orders: 4,
  critical_escalations_count: 2,
  total_weight_kg: 1750.0,
  total_volume_m3: 14.5,
  total_value_lkr: 2887000,
  chilled_orders_count: 2,
  ambient_orders_count: 2,
  van_restricted_count: 2,
  reasons_breakdown: {
    insufficient_reefer_capacity: 1,
    van_access_shortage: 1,
    time_budget_limit: 1,
    fuel_quota_exceeded: 1,
    manual_dispatcher_override: 0,
  },
};

export const INITIAL_DEFERRAL_AUDIT_LOGS: DeferralAuditLog[] = [
  {
    id: "def-01",
    order_id: "ord-cov-01",
    order_ref: "S1-004",
    outlet_id: "OUT004",
    outlet_name: "Waypoint Fresh - Wattala",
    brand: "Fresh",
    brand_id: "brand-fresh-01",
    district: "Gampaha",
    dispatch_date: "2026-10-01",
    deferral_reason: "van_access_shortage",
    limiting_resource: "volume_cap",
    decision_maker_staff_id: "EMP-001",
    decision_maker_name: "K. Jayawardena",
    decision_maker_role: "Lead Dispatcher",
    total_weight_kg: 540.0,
    total_volume_m3: 3.2,
    total_value_lkr: 345000,
    temp_requirement: "chilled",
    dock_type: "street",
    notes:
      "Street parking in Wattala constrained to van access only. 4 reefer vans already allocated to Wave 1. Deferred with mandatory escalation.",
    created_at: "2026-10-01T04:15:22Z",
  },
  {
    id: "def-02",
    order_id: "ord-cov-02",
    order_ref: "S1-018",
    outlet_id: "OUT018",
    outlet_name: "Waypoint Fresh - Kandy City Centre",
    brand: "Fresh",
    brand_id: "brand-fresh-01",
    district: "Kandy",
    dispatch_date: "2026-10-01",
    deferral_reason: "insufficient_reefer_capacity",
    limiting_resource: "time_budget",
    decision_maker_staff_id: "EMP-001",
    decision_maker_name: "K. Jayawardena",
    decision_maker_role: "Lead Dispatcher",
    total_weight_kg: 620.0,
    total_volume_m3: 4.1,
    total_value_lkr: 412000,
    temp_requirement: "chilled",
    dock_type: "mall_bay",
    notes:
      "Mall delivery window 09:00 - 11:00 AM caused driver shift to exceed 270 min morning budget. Priority 1 lock-in tomorrow.",
    created_at: "2026-10-01T04:22:10Z",
  },
  {
    id: "def-03",
    order_id: "ord-cov-03",
    order_ref: "S1-032",
    outlet_id: "OUT032",
    outlet_name: "Waypoint Style - Havelock Town",
    brand: "Style",
    brand_id: "brand-style-01",
    district: "Colombo",
    dispatch_date: "2026-10-01",
    deferral_reason: "time_budget_limit",
    limiting_resource: "time_budget",
    decision_maker_staff_id: "EMP-004",
    decision_maker_name: "S. Fernando",
    decision_maker_role: "Senior Dispatcher",
    total_weight_kg: 380.0,
    total_volume_m3: 4.8,
    total_value_lkr: 680000,
    temp_requirement: "ambient",
    dock_type: "rear_dock",
    notes:
      "Heavy congestion along baseline corridor would cause driver timeout. Reallocated to tomorrow 06:00 AM departure.",
    created_at: "2026-10-01T05:01:45Z",
  },
  {
    id: "def-04",
    order_id: "ord-cov-04",
    order_ref: "S1-045",
    outlet_id: "OUT045",
    outlet_name: "Waypoint Tech - Negombo Retail Hub",
    brand: "Tech",
    brand_id: "brand-tech-01",
    district: "Gampaha",
    dispatch_date: "2026-10-01",
    deferral_reason: "fuel_quota_exceeded",
    limiting_resource: "fleet_downtime",
    decision_maker_staff_id: "EMP-001",
    decision_maker_name: "K. Jayawardena",
    decision_maker_role: "Lead Dispatcher",
    total_weight_kg: 210.0,
    total_volume_m3: 2.4,
    total_value_lkr: 1450000,
    temp_requirement: "ambient",
    dock_type: "rear_dock",
    notes:
      "Assigned vehicle NP-4811 placed in Peliyagoda workshop for scheduled brake pad overhaul. Released tomorrow 04:00 AM.",
    created_at: "2026-10-01T05:18:00Z",
  },
  {
    id: "def-05",
    order_id: "ord-cov-05",
    order_ref: "S1-089",
    outlet_id: "OUT089",
    outlet_name: "Waypoint Fresh - Panadura Central",
    brand: "Fresh",
    brand_id: "brand-fresh-01",
    district: "Kalutara",
    dispatch_date: "2026-09-30",
    deferral_reason: "insufficient_reefer_capacity",
    limiting_resource: "weight_cap",
    decision_maker_staff_id: "EMP-004",
    decision_maker_name: "S. Fernando",
    decision_maker_role: "Senior Dispatcher",
    total_weight_kg: 780.0,
    total_volume_m3: 4.9,
    total_value_lkr: 520000,
    temp_requirement: "chilled",
    dock_type: "rear_dock",
    notes:
      "Kalutara reefer truck filled to 99.2% capacity. Order deferred yesterday, successfully dispatched today on Trip 1.",
    created_at: "2026-09-30T04:30:10Z",
  },
  {
    id: "def-06",
    order_id: "ord-cov-06",
    order_ref: "S1-102",
    outlet_id: "OUT102",
    outlet_name: "Waypoint Style - Kandy Mall Dock",
    brand: "Style",
    brand_id: "brand-style-01",
    district: "Kandy",
    dispatch_date: "2026-09-30",
    deferral_reason: "van_access_shortage",
    limiting_resource: "volume_cap",
    decision_maker_staff_id: "EMP-001",
    decision_maker_name: "K. Jayawardena",
    decision_maker_role: "Lead Dispatcher",
    total_weight_kg: 310.0,
    total_volume_m3: 3.8,
    total_value_lkr: 720000,
    temp_requirement: "ambient",
    dock_type: "mall_bay",
    notes:
      "Kandy Mall access requires van-only clearance. Dispatched on secondary afternoon wave.",
    created_at: "2026-09-30T05:40:00Z",
  },
];
