import type { LiveVehicleTelemetry, VehicleTelemetry } from "./types";

const INITIAL_LIVE_VEHICLES: LiveVehicleTelemetry[] = [
  {
    id: 1,
    vehicle_id: "VEH001",
    reg_number: "NP-4811",
    model_name: "Isuzu ELF NPR Reefer",
    vehicle_type: "14ft Cold Reefer Lorry",
    vehicle_category: "truck",
    temp: "reefer",
    reefer_temp_celsius: 3.2,
    ambient_temp_celsius: 28.5,
    fuel_level_pct: 82.5,
    battery_pct: 95.0,
    speed_kmh: 42.0,
    heading_deg: 185,
    latitude: 6.9271,
    longitude: 79.8612,
    brand: "Fresh",
    depot: "Peliyagoda",
    image_url: "/vehicle-images/freeze.png",
    driver_name: "Saman Perera",
    driver_phone: "+94 77 123 4567",
    status: "en_route",
    weight_percentage: 80,
    weight_kg: 3360,
    max_weight_kg: 4200,
    volume_percentage: 80,
    volume_cbm: 22.4,
    max_volume_cbm: 28.0,
    crates_count: 84,
    next_stop: "Waypoint Fresh - Fort Dock",
    next_stop_eta: "07:30 AM",
    stops_total: 5,
    stops_completed: 2,
    recorded_at: new Date().toISOString(),
  },
  {
    id: 2,
    vehicle_id: "VEH002",
    reg_number: "WP-3021",
    model_name: "Mitsubishi Fuso Canter",
    vehicle_type: "16ft Ambient Freight Lorry",
    vehicle_category: "truck",
    temp: "ambient",
    reefer_temp_celsius: null,
    ambient_temp_celsius: 29.1,
    fuel_level_pct: 74.0,
    battery_pct: 90.0,
    speed_kmh: 0.0,
    heading_deg: 95,
    latitude: 6.9147,
    longitude: 79.8732,
    brand: "Style",
    depot: "Peliyagoda",
    image_url: "/vehicle-images/dry.png",
    driver_name: "Ruwan Silva",
    driver_phone: "+94 71 456 7890",
    status: "delayed",
    weight_percentage: 88,
    weight_kg: 5280,
    max_weight_kg: 6000,
    volume_percentage: 91,
    volume_cbm: 20.0,
    max_volume_cbm: 22.0,
    crates_count: 120,
    next_stop: "Waypoint Tech - Town Hall Bay",
    next_stop_eta: "09:30 AM",
    stops_total: 6,
    stops_completed: 2,
    recorded_at: new Date().toISOString(),
  },
  {
    id: 3,
    vehicle_id: "VEH003",
    reg_number: "WP-NB-5521",
    model_name: "Nissan NV350 Caravan",
    vehicle_type: "Express Delivery Van",
    vehicle_category: "van",
    temp: "ambient",
    reefer_temp_celsius: null,
    ambient_temp_celsius: 28.8,
    fuel_level_pct: 68.0,
    battery_pct: 98.0,
    speed_kmh: 36.5,
    heading_deg: 210,
    latitude: 6.8654,
    longitude: 79.8682,
    brand: "Fresh",
    depot: "Peliyagoda",
    image_url: "/vehicle-images/van.png",
    driver_name: "Dinesh Fernando",
    driver_phone: "+94 76 987 6543",
    status: "en_route",
    weight_percentage: 77,
    weight_kg: 1390,
    max_weight_kg: 1800,
    volume_percentage: 78,
    volume_cbm: 5.6,
    max_volume_cbm: 7.2,
    crates_count: 38,
    next_stop: "Waypoint Fresh - Dehiwala",
    next_stop_eta: "07:45 AM",
    stops_total: 4,
    stops_completed: 1,
    recorded_at: new Date().toISOString(),
  },
  {
    id: 4,
    vehicle_id: "VEH004",
    reg_number: "WP-NF-9921",
    model_name: "Toyota Dyna 150",
    vehicle_type: "14ft Ambient Freight Lorry",
    vehicle_category: "truck",
    temp: "ambient",
    reefer_temp_celsius: null,
    ambient_temp_celsius: 29.4,
    fuel_level_pct: 89.0,
    battery_pct: 92.0,
    speed_kmh: 0.0,
    heading_deg: 0,
    latitude: 6.9366,
    longitude: 79.8454,
    brand: "Tech",
    depot: "Peliyagoda",
    image_url: "/vehicle-images/dry.png",
    driver_name: "Kasun Jayawardena",
    driver_phone: "+94 77 345 6789",
    status: "at_stop",
    weight_percentage: 85,
    weight_kg: 4420,
    max_weight_kg: 5200,
    volume_percentage: 87,
    volume_cbm: 15.6,
    max_volume_cbm: 18.0,
    crates_count: 72,
    next_stop: "Waypoint Tech - Town Hall Bay",
    next_stop_eta: "10:15 AM",
    stops_total: 5,
    stops_completed: 4,
    recorded_at: new Date().toISOString(),
  },
  {
    id: 5,
    vehicle_id: "VEH005",
    reg_number: "WP-NC-1089",
    model_name: "Tata Ace Mega Express",
    vehicle_type: "Express Delivery Van",
    vehicle_category: "van",
    temp: "ambient",
    reefer_temp_celsius: null,
    ambient_temp_celsius: 28.2,
    fuel_level_pct: 61.5,
    battery_pct: 94.0,
    speed_kmh: 28.0,
    heading_deg: 320,
    latitude: 6.9512,
    longitude: 79.8781,
    brand: "Fresh",
    depot: "Peliyagoda",
    image_url: "/vehicle-images/van.png",
    driver_name: "Pradeep Kumara",
    driver_phone: "+94 72 234 5678",
    status: "en_route",
    weight_percentage: 64,
    weight_kg: 1150,
    max_weight_kg: 1800,
    volume_percentage: 67,
    volume_cbm: 4.8,
    max_volume_cbm: 7.2,
    crates_count: 45,
    next_stop: "Waypoint Fresh - Wellawatte",
    next_stop_eta: "08:00 AM",
    stops_total: 4,
    stops_completed: 2,
    recorded_at: new Date().toISOString(),
  },
];

const liveState = INITIAL_LIVE_VEHICLES.map((v) => ({ ...v }));

export async function getLiveTelemetryMock(): Promise<LiveVehicleTelemetry[]> {
  const ts = new Date().toISOString();
  return liveState.map((v) => {
    if (v.status === "en_route") {
      const headingRad = ((v.heading_deg || 0) * Math.PI) / 180;
      const step = 0.0004;
      v.latitude += Math.cos(headingRad) * step;
      v.longitude += Math.sin(headingRad) * step;
      v.heading_deg = ((v.heading_deg || 0) + (Math.random() > 0.5 ? 2 : -2) + 360) % 360;
    }
    v.recorded_at = ts;
    return { ...v };
  });
}

export async function getVehicleLatestTelemetryMock(
  vehicleId: string
): Promise<VehicleTelemetry> {
  const live = liveState.find(
    (v) => v.vehicle_id === vehicleId || v.reg_number === vehicleId
  );
  if (live) {
    return {
      id: live.id,
      vehicle_id: live.vehicle_id,
      trip_id: live.trip_id,
      latitude: live.latitude,
      longitude: live.longitude,
      speed_kmh: live.speed_kmh,
      heading_deg: live.heading_deg,
      reefer_temp_celsius: live.reefer_temp_celsius,
      ambient_temp_celsius: live.ambient_temp_celsius,
      fuel_level_pct: live.fuel_level_pct,
      battery_pct: live.battery_pct,
      recorded_at: live.recorded_at,
    };
  }
  return {
    vehicle_id: vehicleId,
    latitude: 6.9649,
    longitude: 79.8872,
    speed_kmh: 0,
    heading_deg: 0,
    fuel_level_pct: 100,
    recorded_at: new Date().toISOString(),
  };
}
