import type { AllocationDetail, AllocationKpis, AllocationSummary } from "./types";

export const MOCK_ALLOCATION_SUMMARIES: AllocationSummary[] = [
  {
    id: "trip-01",
    trip_code: "RT-14",
    dispatch_date: "2026-10-03",
    trip_sequence: 1,
    vehicle_id: "veh-01",
    driver_id: "drv-01",
    depot_id: "depot-pel",
    brand_id: "brand-fresh",
    district_id: "dist-colombo",
    status: "dispatched",
    outbound_travel_min: 45,
    inter_stop_travel_min: 30,
    total_handling_min: 60,
    total_trip_duration_min: 135,
    total_distance_km: 42.5,
    weight_utilization_pct: 80.0,
    volume_utilization_pct: 80.0,
    total_packages: 80,
    total_orders: 3,
    cargo_value_lkr: 1450000.0,
    total_payload_kg: 3360,
    total_volume_m3: 22.4,
    weight_cap_kg: 4200,
    volume_cap_m3: 28.0,
    vehicle_reg_number: "NP-4811",
    vehicle_model: "Isuzu ELF NPR",
    vehicle_type: "truck",
    driver_name: "Saman Perera",
    driver_phone: "+94 77 123 4567",
    depot_name: "Peliyagoda Central DC",
    brand_name: "Waypoint Fresh",
    district_name: "Colombo",
  },
  {
    id: "trip-02",
    trip_code: "RT-08",
    dispatch_date: "2026-10-03",
    trip_sequence: 1,
    vehicle_id: "veh-02",
    driver_id: "drv-02",
    depot_id: "depot-pel",
    brand_id: "brand-style",
    district_id: "dist-gampaha",
    status: "loading",
    outbound_travel_min: 60,
    inter_stop_travel_min: 45,
    total_handling_min: 90,
    total_trip_duration_min: 195,
    total_distance_km: 58.0,
    weight_utilization_pct: 82.0,
    volume_utilization_pct: 81.0,
    total_packages: 168,
    total_orders: 3,
    cargo_value_lkr: 2890000.0,
    total_payload_kg: 4920,
    total_volume_m3: 17.8,
    weight_cap_kg: 6000,
    volume_cap_m3: 22.0,
    vehicle_reg_number: "WP-NE-3120",
    vehicle_model: "Mitsubishi Fuso Canter",
    vehicle_type: "truck",
    driver_name: "Ruwan Silva",
    driver_phone: "+94 71 456 7890",
    depot_name: "Peliyagoda Central DC",
    brand_name: "Waypoint Style",
    district_name: "Gampaha",
  },
  {
    id: "trip-03",
    trip_code: "RT-22",
    dispatch_date: "2026-10-03",
    trip_sequence: 1,
    vehicle_id: "veh-03",
    driver_id: "drv-03",
    depot_id: "depot-pel",
    brand_id: "brand-tech",
    district_id: "dist-colombo",
    status: "dispatched",
    outbound_travel_min: 30,
    inter_stop_travel_min: 25,
    total_handling_min: 45,
    total_trip_duration_min: 100,
    total_distance_km: 24.0,
    weight_utilization_pct: 77.0,
    volume_utilization_pct: 78.0,
    total_packages: 52,
    total_orders: 3,
    cargo_value_lkr: 4120000.0,
    total_payload_kg: 1390,
    total_volume_m3: 5.6,
    weight_cap_kg: 1800,
    volume_cap_m3: 7.2,
    vehicle_reg_number: "WP-NB-5521",
    vehicle_model: "Nissan NV350 Caravan",
    vehicle_type: "van",
    driver_name: "Dinesh Fernando",
    driver_phone: "+94 76 987 6543",
    depot_name: "Peliyagoda Central DC",
    brand_name: "Waypoint Tech",
    district_name: "Colombo",
  },
  {
    id: "trip-04",
    trip_code: "RT-05",
    dispatch_date: "2026-10-03",
    trip_sequence: 1,
    vehicle_id: "veh-04",
    driver_id: "drv-04",
    depot_id: "depot-pel",
    brand_id: "brand-style",
    district_id: "dist-colombo",
    status: "scheduled",
    outbound_travel_min: 50,
    inter_stop_travel_min: 40,
    total_handling_min: 75,
    total_trip_duration_min: 165,
    total_distance_km: 48.2,
    weight_utilization_pct: 85.0,
    volume_utilization_pct: 87.0,
    total_packages: 138,
    total_orders: 3,
    cargo_value_lkr: 1980000.0,
    total_payload_kg: 4420,
    total_volume_m3: 15.6,
    weight_cap_kg: 5200,
    volume_cap_m3: 18.0,
    vehicle_reg_number: "WP-NF-9921",
    vehicle_model: "Toyota Dyna 150",
    vehicle_type: "truck",
    driver_name: "Kasun Jayawardena",
    driver_phone: "+94 77 345 6789",
    depot_name: "Peliyagoda Central DC",
    brand_name: "Waypoint Style",
    district_name: "Colombo",
  },
];

export const MOCK_ALLOCATION_DETAILS: Record<string, AllocationDetail> = {
  "trip-01": {
    trip: {
      id: "trip-01",
      trip_code: "RT-14",
      dispatch_date: "2026-10-03",
      trip_sequence: 1,
      vehicle_id: "veh-01",
      driver_id: "drv-01",
      depot_id: "depot-pel",
      brand_id: "brand-fresh",
      district_id: "dist-colombo",
      status: "dispatched",
      outbound_travel_min: 45,
      inter_stop_travel_min: 30,
      total_handling_min: 60,
      total_trip_duration_min: 135,
      total_distance_km: 42.5,
      seal_number: "SL-90821-B",
    },
    vehicle: {
      id: "veh-01",
      vehicle_id: "VEH001",
      reg_number: "NP-4811",
      model_name: "Isuzu ELF NPR",
      type: "truck",
      temp: "reefer",
      weight_cap_kg: 4200,
      volume_cap_m3: 28.0,
      km_per_l: 7.5,
      weekly_fuel_quota_l: 340,
    },
    driver: {
      id: "drv-01",
      name: "Saman Perera",
      phone: "+94 77 123 4567",
      license_number: "DL-90821-WP-89",
    },
    depot: {
      id: "depot-pel",
      code: "PEL",
      name: "Peliyagoda Central DC",
    },
    brand: {
      id: "brand-fresh",
      code: "FRESH",
      name: "Waypoint Fresh",
    },
    district: {
      id: "dist-colombo",
      name: "Colombo",
    },
    legs: [
      {
        id: "leg-01-0",
        trip_id: "trip-01",
        seq: 0,
        from_point: "DEPOT",
        to_outlet_id: "outlet-out001",
        order_id: "ord-101",
        distance_km: 14.5,
        planned_depart_time: "06:30:00",
        planned_arrival_time: "07:15:00",
        status: "completed",
        outlet_name: "Waypoint Fresh Wattala",
        outlet_code: "OUT001",
        address: "Negombo Road, Wattala",
        dock_type: "rear_dock",
        parking_constraint: "normal",
        window_open_time: "05:00:00",
        window_close_time: "08:00:00",
        contact_phone: "+94 11 293 8471",
        crates_count: 32,
        items: [
          {
            id: "crate-101",
            order_id: "ord-101",
            order_item_id: "oi-101",
            sku: "FRE-MILK-1L",
            item_name: "Fresh Whole Milk 1L",
            package_code: "PKG-90412-A",
            requested_qty: 20,
            unit_weight_kg: 1.05,
            unit_volume_m3: 0.0012,
            unit_price: 450.0,
            special_handling_code: "COL",
          },
          {
            id: "crate-102",
            order_id: "ord-101",
            order_item_id: "oi-102",
            sku: "FRE-CURD-500G",
            item_name: "Buffalo Curd Pot 500g",
            package_code: "PKG-90412-B",
            requested_qty: 12,
            unit_weight_kg: 0.55,
            unit_volume_m3: 0.0008,
            unit_price: 380.0,
            special_handling_code: "COL",
          },
        ],
      },
      {
        id: "leg-01-1",
        trip_id: "trip-01",
        seq: 1,
        from_point: "outlet-out001",
        to_outlet_id: "outlet-out002",
        order_id: "ord-102",
        distance_km: 18.2,
        planned_depart_time: "07:45:00",
        planned_arrival_time: "08:30:00",
        status: "in_transit",
        outlet_name: "Keells Super - Kollupitiya",
        outlet_code: "OUT002",
        address: "Dharmapala Mawatha, Kollupitiya",
        dock_type: "rear_dock",
        parking_constraint: "normal",
        window_open_time: "05:00:00",
        window_close_time: "08:00:00",
        contact_phone: "+94 11 257 3910",
        crates_count: 28,
      },
      {
        id: "leg-01-2",
        trip_id: "trip-01",
        seq: 2,
        from_point: "outlet-out002",
        to_outlet_id: "outlet-out003",
        order_id: "ord-103",
        distance_km: 9.8,
        planned_depart_time: "09:00:00",
        planned_arrival_time: "09:30:00",
        status: "pending",
        outlet_name: "Arpico Supercentre - Hyde Park",
        outlet_code: "OUT003",
        address: "Hyde Park Corner, Colombo 02",
        dock_type: "street",
        parking_constraint: "normal",
        window_open_time: "05:00:00",
        window_close_time: "08:00:00",
        contact_phone: "+94 11 230 4819",
        crates_count: 20,
      },
    ],
    summary: {
      total_orders: 3,
      total_packages: 80,
      total_payload_kg: 3360,
      total_volume_m3: 22.4,
      cargo_value_lkr: 1450000.0,
      weight_utilization_pct: 80.0,
      volume_utilization_pct: 80.0,
    },
  },
};

export const MOCK_ALLOCATION_KPIS: AllocationKpis = {
  total_trips: 4,
  active_trips: 2,
  completed_trips: 0,
  total_packages_allocated: 438,
  total_weight_kg: 14090,
  total_volume_m3: 61.4,
  total_cargo_value_lkr: 10440000.0,
  avg_weight_utilization_pct: 81.0,
  avg_volume_utilization_pct: 81.5,
  fully_utilized_trips: 3,
};
